name: UI Unittest

# trigger:
#   branches:
#     include:
#       - main

#   paths:
#     include:
#       - src/angular-swa/*

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  nodeVer: '18.17.0'
  app: angular-swa  
  apploc: src/$(app)/

stages:
- stage: UnitTest
  displayName: Jasmine UnitTest

  jobs:
    - job: Test
      
      steps:       
      - task: NodeTool@0
        inputs:
          versionSpec: $(nodeVer)
        displayName: Install Node $(nodeVer)
        
      - script: npm i -g @angular/cli@17        
      
      - task: Cache@2
        displayName: Setup Node Cache
        inputs:
            key: '$(System.DefaultWorkingDirectory)/$(apploc)/package-lock.json'
            path: '$(System.DefaultWorkingDirectory)/$(apploc)/node_modules'
            cacheHitVar: 'npmCache'

      - script: npm install
        displayName: 'npm install'
        workingDirectory: $(apploc)
        condition: eq(variables['npmCache'],False)
      
      - script: ng test --watch false --code-coverage true --browsers ChromeHeadless
        displayName: 'Test Angular'
        workingDirectory:  $(apploc)

      # - task: Npm@1
      #   displayName: 'Test Angular'
      #   inputs:
      #     command: 'custom'
      #     customCommand: 'run test -- --watch false -- --code-coverage true'
      #     workingDir: $(System.DefaultWorkingDirectory)/$(apploc)
          
      - task: PublishTestResults@2
        displayName: 'Publish Angular test results'
        condition: succeededOrFailed()
        inputs:
          searchFolder: $(System.DefaultWorkingDirectory)/$(apploc)/junit
          testRunTitle: Angular
          testResultsFormat: JUnit
          testResultsFiles: "**/TESTS*.xml"

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage Angular results'
        condition: succeededOrFailed()
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/$(apploc)/coverage/cobertura-coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/src/AngularApp/coverage'
          failIfCoverageEmpty: false
